### ISSUE TITLE
Sort timezones in new contest form

### ISSUE THREAD

**Issue by kapitan-iglu** [airsports-no/airsportslivetracking#12]
In select field `id_time_zone` of new contest creation form `/display/contest/create/` values are randomly ordered (order sometimes changes between page reloads). Expected behavior is to sort values alphabetically.

I thing that a year before the values was properly ordered.

**Comment by kolaf** [comment]
Waiting for new release of django-timezone-field, https://github.com/mfogel/django-timezone-field/pull/123

**Comment by kolaf** [comment]
Updated library has been released, will shortly roll out that update.
