### ISSUE TITLE
Contestant speed should defaults to registered team's speed

### ISSUE THREAD

**Issue by kapitan-iglu** [airsports-no/airsportslivetracking#13]
When new team is registering to the contest using admin web interface, team's desired speed is entered. Once this team is chosen as new contestant to the navigation task, same speed should be pre-filled into the "Air Speed" field. Now there is fixed value "70kts".

Possible solution: default value of "Air Speed" field should be "blank" with placeholder "Inherit from team registration". There will be always option to override speed if some value is entered.

**Comment by kolaf** [comment]
Good point, I'll put it on my list.
