### ISSUE TITLE
Consider stopping a trip some time after finishing point 

### ISSUE THREAD

**Issue by olvesh** [airsports-no/airsportslivetracking#16]
If contestants forget turning of logging when flying a training trip, the whole route will be logged. 

Some (perhaps configurable time) after a plane passes FP or after the total time of route the logging could be disabled for that route/crew combo

<img width="300" alt="image" src="https://github.com/airsports-no/airsportslivetracking/assets/220643/a8c17e1d-5015-48e6-8d73-f236f03f3357">

**Comment by kolaf** [comment]
Tracking automatically stops after finished_by_time. Perhaps we need better tools to configure this for self registration and contestant scheduling.
